version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.2
    working_directory: /go/src/github.com/panicpanicpanic/filament
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
